# Generated by Django 6.0.2 on 2026-02-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha en que se realizó el pago')),
                ('periodo', models.CharField(max_length=100, verbose_name='Período administrado')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/', verbose_name='Comprobante (imagen o PDF)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('aprobado', 'Aprobado / Pagado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=30, verbose_name='Estado del pago')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Comentarios del administrador')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='apartamentos.apartamento', verbose_name='Apartamento')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
