# Generated by Django 6.0.2 on 2026-02-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Número, código o referencia única del apartamento', max_length=30, unique=True, verbose_name='Identificador / Número de apartamento')),
                ('bloque_o_torre', models.CharField(blank=True, max_length=10, verbose_name='Torre / Bloque')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Área (m²)')),
                ('estado', models.CharField(choices=[('residiendo', 'Residiendo (propietario viviendo)'), ('arrendado', 'Arrendado (alquilado)'), ('en_venta', 'En venta'), ('desocupado', 'Desocupado / Vacío'), ('en_obra_mantenimiento', 'En obra o mantenimiento'), ('bloqueado', 'Bloqueado / Embargado / Prohibido uso')], default='desocupado', max_length=30, verbose_name='Estado de la vivienda')),
                ('piso', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Piso')),
                ('notas', models.TextField(blank=True, verbose_name='Notas / Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'ordering': ['identificador'],
            },
        ),
    ]
