# Generated by Django 6.0.2 on 2026-02-19 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='ocupante_actual',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'residente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartamentos_ocupados', to=settings.AUTH_USER_MODEL, verbose_name='Ocupante / Residente actual'),
        ),
        migrations.AddIndex(
            model_name='apartamento',
            index=models.Index(fields=['identificador'], name='apartamento_identif_f2d11f_idx'),
        ),
        migrations.AddIndex(
            model_name='apartamento',
            index=models.Index(fields=['estado'], name='apartamento_estado_daa1ae_idx'),
        ),
    ]
