# Generated by Django 6.0.2 on 2026-02-15 22:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartamento',
            options={'ordering': ['identificador'], 'verbose_name': 'Apartamento', 'verbose_name_plural': 'Apartamentos'},
        ),
        migrations.RemoveField(
            model_name='apartamento',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='apartamento',
            name='residente',
        ),
        migrations.RemoveField(
            model_name='apartamento',
            name='torre',
        ),
        migrations.AddField(
            model_name='apartamento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='bloque_o_torre',
            field=models.CharField(blank=True, help_text='Ej: A, B, C, Norte, Sur... (opcional)', max_length=10, verbose_name='Torre / Bloque'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 15, 22, 18, 39, 75501, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartamento',
            name='identificador',
            field=models.CharField(default='2025-01-01 00:00:00+00:00', help_text='Número, código o referencia única del apartamento (ej: 101, 1503, PH-02)', max_length=20, unique=True, verbose_name='Identificador / Número de apartamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartamento',
            name='notas',
            field=models.TextField(blank=True, help_text='Ej: remodelado 2024, tiene mascota, problemas con parqueadero, etc.', verbose_name='Notas / Observaciones'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='ocupante_actual',
            field=models.ForeignKey(blank=True, help_text='Persona que vive o arrienda actualmente (si aplica)', limit_choices_to={'rol': 'residente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartamentos_ocupados', to=settings.AUTH_USER_MODEL, verbose_name='Ocupante / Residente actual'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='piso',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Área (m²)'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='estado',
            field=models.CharField(choices=[('residiendo', 'Residiendo (propietario viviendo)'), ('arrendado', 'Arrendado (alquilado)'), ('en_venta', 'En venta'), ('desocupado', 'Desocupado / Vacío'), ('en_obra_mantenimiento', 'En obra o mantenimiento'), ('bloqueado', 'Bloqueado / Embargado / Prohibido uso')], default='desocupado', max_length=30, verbose_name='Estado de la vivienda'),
        ),
        migrations.AddIndex(
            model_name='apartamento',
            index=models.Index(fields=['identificador'], name='apartamento_identif_f2d11f_idx'),
        ),
        migrations.AddIndex(
            model_name='apartamento',
            index=models.Index(fields=['estado'], name='apartamento_estado_daa1ae_idx'),
        ),
    ]
