# Generated by Django 6.0.2 on 2026-02-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['-destacado', '-fecha_publicacion']},
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='fecha_creacion',
            new_name='fecha_publicacion',
        ),
    ]
