# Generated by Django 6.0.2 on 2026-02-23 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_alter_anuncio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={},
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
